import React from "react";
import PropTypes from "prop-types";
import clsx from "clsx";
import Container from "@material-ui/core/Container";
import Box from "@material-ui/core/Box";
import useMediaQuery from "@material-ui/core/useMediaQuery";
import { useTheme } from "@material-ui/core/styles";
import Grid from "@material-ui/core/Grid";
import Hidden from "@material-ui/core/Hidden";
import Accordion from "@material-ui/core/Accordion";
import AccordionSummary from "@material-ui/core/AccordionSummary";
import AccordionDetails from "@material-ui/core/AccordionDetails";
import ExpandMoreIcon from "@material-ui/icons/ExpandMore";
import Typography from "@material-ui/core/Typography";
import { withTranslation } from "~/i18n";
import { useText, useTextAlign } from "~/theme/common";
import imgAPI from "~/public/images/imgAPI";
import useStyles from "./faq-style";

const faqData = [
  {
    q: "What is proof of stake in blockchain?",
    a: "Proof of Stake (PoS) concept states that a person can mine or validate block transactions according to how many coins he holds. This means that the more coins are owned by a node, the more mining power he has. There are many variants of the standard PoS, such as leased, delegated, or nominated PoS.",
  },
  {
    q: "What does Smart Nodes staking investment platform do?",
    a: "Smart Nodes is a reliable staking platform that allows users and businesses to earn rewards on their holdings for a selected set of high quality supported blockchains. We try to lower the barrier for new users by creating easy to follow documentation and providing help among various crypto communities. ",
  },
  {
    q: "What are the minimum and maximum deposit?",
    a: "Smart Nodes allows anyone to earn rewards on deposits from $1 to an unlimited amount.",
  },
  {
    q: "How much does it cost to stake with Smart Nodes ?",
    a: "We only have a small performance fee, that is, we take a small portion of the earnings generated by the node. This commission varies between projects but rounds the 5%. Take into account that maintaining a reliable and fault-tolerant infrastructure has very high server and administration costs.",
  },
  {
    q: "How do you keep my funds safe?",
    a: "We do not keep any funds except for the fees generated by the node. PoS blockchains have evolved and they no longer require to transfer funds to the validator, you just delegate your voting power by submitting a transaction. ",
  },
  {
    q: "Staking Disclaimer",
    a: `Nodes are non-custodial, we do not hold any money on our end. Users are responsible for saving and protecting their wallets.

    Some blockchains do have slashing punishment for bad nodes, our expert team have a continuous monitoring over all the nodes to prevent any related issue. As a result of that, our nodes have never been slashed. It is extremely difficult to happen, but if it that ever occurs, we will not take any responsibility on any losses.
    
    Currencies are volatile and their price may vary a lot. Please, do not take our site as advice to invest. You will be responsible for the losses that may result.`,
  },
];

function Faq(props) {
  const classes = useStyles();
  const text = useText();
  const align = useTextAlign();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
  const { t } = props;
  const [expanded, setExpanded] = React.useState(0);
  const handleChange = (panel) => (event, newExpanded) => {
    setExpanded(newExpanded ? panel : false);
  };
  return (
    <div className={classes.root}>
      <Container fixed>
        <Grid container spacing={6}>
          <Grid item md={6}>
            <Box mb={3}>
              <h4
                className={clsx(text.title2, isMobile ? align.textCenter : "")}
              >
                What is Staking?
              </h4>
            </Box>
            <p
              className={clsx(
                text.subtitle2,
                isMobile ? align.textCenter : align.textLeft
              )}
            >
              Proof of Stake blockchains use staking as the security mechanism
              to keep nodes honest. You can help protect networks, while holding
              your crypto in your wallet, delegating them to a trusted
              validator. In return, you get rewards.
            </p>
            <Hidden smDown>
              <div className={classes.illustration}>
                <img
                  src={imgAPI.cryptoInner[7]}
                  data-2d={imgAPI.cryptoInner[6]}
                  data-3d={imgAPI.cryptoInner[7]}
                  className="img-2d3d"
                  alt="faq 3d"
                />
              </div>
            </Hidden>
          </Grid>
          <Grid item md={6}>
            <div className={classes.accordion}>
              {faqData.map((item, index) => (
                <div className={classes.item} key={index.toString()}>
                  <Accordion
                    classes={{
                      root: classes.paper,
                    }}
                    expanded={expanded === index}
                    onChange={handleChange(index)}
                  >
                    <AccordionSummary
                      classes={{
                        content: classes.content,
                        expanded: classes.expanded,
                      }}
                    >
                      <Typography className={classes.heading}>
                        {item.q}
                      </Typography>
                      <ExpandMoreIcon className={classes.icon} />
                    </AccordionSummary>
                    <AccordionDetails
                      classes={{
                        root: classes.detail,
                      }}
                    >
                      <Typography>{item.a}</Typography>
                    </AccordionDetails>
                  </Accordion>
                </div>
              ))}
            </div>
          </Grid>
        </Grid>
      </Container>
    </div>
  );
}

Faq.propTypes = {
  t: PropTypes.func.isRequired,
};

export default withTranslation(["common"])(Faq);
